
# -------------------------------
# Pod: Mounts a Secret as a volume
# -------------------------------
apiVersion: v1
kind: Pod
metadata:
  # Name of the Pod
  name: my-pod-volume
spec:
  containers:
  - name: my-container
    # Container image
    image: nginx:stable-alpine

    # Mount the Secret as a volume inside the container
    volumeMounts:
    - name: secret-volume
      # Path inside the container where the Secret will be mounted
      mountPath: /etc/secret

  # Define volumes for the Pod
  volumes:
  - name: secret-volume
    # Use the Secret as the source for this volume
    secret:
      # Reference the Secret by name
      secretName: my-secret

