
---
- name: Install Apache on all hosts
  hosts: all
  become: true   # Use sudo to get root privileges
  tasks:
    - name: Install Apache package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure Apache service is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
